name: Build & Test (Backend)

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]

jobs:
  build:
    name: Build, Test & Coverage
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: ['17']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'
          cache-dependency-path: 'pom.xml'

      - name: Build project (skip tests)
        run: mvn clean install -DskipTests

      - name: Run tests
        run: mvn test

      - name: Generate JaCoCo coverage report
        run: mvn jacoco:report

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco

      - name: Run SonarCloud analysis (via Maven)
        run: mvn verify sonar:sonar -Dsonar.projectKey=AntoineCheminPro_CI-CD-backend-project -Dsonar.organization=antoinechemin -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
